name: Jason Briscoe
favicon: null
layout_spectrum: 0.6288703209720552
typography_spectrum: 0.24278
title: Jason Brisce
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.19196491385810077
  lightness: 0.6834439521189779
  saturation: 0.625
  rhythmicContrast: 0.4768230889458209
purpose: []
